authors: null
dependencies: null
description: null
documentation: null
homepage: null
issues: null
license: null
name: source_control_bitbucket
namespace: jctanner
repository: null
tags: null
version: 2.9.0.dev0
